#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_script_progression --message="Removing Armada Nginx configuration..." --weight=1
ynh_remove_nginx_config

ynh_script_progression --message="Removing Armada files..." --weight=1
ynh_secure_remove --file="$install_dir"

ynh_script_progression --message="Armada removal complete" --last
